development:
  http_timeout: 15
  interval: "1m"
  redis: "localhost:6379"
  domain: "example.com"
  email:
    sender: "picket@example.com"
    receiver: "picket@example.com"
  mailer:
    address: 'smtp.sendgrid.net'
    port: 587
    user_name: 'user'
    password: 'password'
    domain: 'heroku.com'

test:
  http_timeout: 15
  interval: "5m"
  redis: "localhost:6379"
  domain: "example.com"
  email:
    sender: "picket@example.com"
    receiver: "picket@example.com"
  mailer:
    address: 'smtp.sendgrid.net'
    port: 587
    user_name: 'user'
    password: 'password'
    domain: 'heroku.com'

production:
  http_timeout: <%= ENV['HTTP_TIMEOUT'].nil? ? 15 : ENV['HTTP_TIMEOUT'].to_i %>
  interval: <%= ENV['SCHEDULE_INTERVAL'] || "5m" %>
  redis: <%= ENV['REDIS_URL'] %>
  domain: <%= ENV['EMAIL_DOMAIN'] %>
  email:
    sender: <%= ENV['EMAIL_SENDER'] %>
    receiver: <%= ENV['EMAIL_RECEIVER'] %>
  mailer:
    address: 'smtp.sendgrid.net'
    port: 587
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    domain: 'heroku.com'